apiVersion: v1
kind: Namespace
metadata:
  name: demo-file-share

---

apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-account-secret
  namespace: demo-file-share
stringData:
  azurestorageaccountname: stk8sstoragedemo
  azurestorageaccountkey: <AccountKey>

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-file-share
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: pv-file-share-001  # make sure this volumeid is unique for every identical share in the cluster
    volumeAttributes:
      resourceGroup: rg-k8s-storage-demo  # optional, only set this when storage account is not in the same resource group as node
      shareName: k8-file-share
    nodeStageSecretRef:
      name: azure-storage-account-secret # secret name
      namespace: demo-file-share
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock
    - nobrl

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-file-share
  namespace: demo-file-share
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: pv-file-share
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-bridge-file-share
  namespace: demo-file-share
spec:
  selector:
    matchLabels:
      app: api-bridge-file-share
  template:
    metadata:
      labels:
        app: api-bridge-file-share
    spec:
      containers:
        - name: api-bridge-file-share
          image: myacr.azurecr.io/demo/azure-file-share/api:dev
          imagePullPolicy: Always
          volumeMounts:
            - name: vol-file-share
              mountPath: /app/files/azure
      volumes:
        - name: vol-file-share
          persistentVolumeClaim:
            claimName: pvc-file-share

---

# Service to expose the Pod to outside
apiVersion: v1
kind: Service
metadata:
  name: api-bridge-file-share
  namespace: demo-file-share
spec:
  type: LoadBalancer
  ports:
    - port: 5050
      targetPort: 80
      protocol: TCP
  selector:
    app: api-bridge-file-share
    
---